version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@polkadot/api"
    versions:
    - 4.6.2
    - 4.7.1
  - dependency-name: "@polkadot/ui-keyring"
    versions:
    - 0.74.1
  - dependency-name: "@polkadot/networks"
    versions:
    - 6.2.1
  - dependency-name: "@polkadot/ui-settings"
    versions:
    - 0.74.1
  - dependency-name: "@polkadot/types"
    versions:
    - 4.3.1
    - 4.5.1
    - 4.6.2
